pipeline:
  name: DEMO-TEST2
  identifier: DEMOTEST2
  projectIdentifier: pi
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dockerrag
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-gcp
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "started"
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: royjith/docker
                    tags:
                      - v1
                    caching: true
